name = "CompBayesRegistry"
uuid = "c2cbabd0-f95d-467b-bdda-e7a1cfc8d694"
repo = "https://github.com/compbayes/CompBayesRegistry.git"
description = "Private registry for Computational Bayes group"

[packages]
a6a4a4df-ba9f-45e9-bafc-bec3296762b9 = { name = "Utils", path = "U/Utils" }
